:development:
  bucket: 'biezvo-contens-test'
  host: 'd715cecfo4htx.cloudfront.net'
:staging:
  bucket: 'bizevo-contents-staging'
  host: 'd34xwkrqkk4skr.cloudfront.net'
:production:
  bucket: 'bizevo-contents'
  host: ''
:test:
  bucket: 'bizevo-contents-test'
  host: ''
