:development:
  bucket: 'bizevo-contents-development'
  host: 'd3q38qwpamobja.cloudfront.net'
:staging:
  bucket: 'bizevo-contents-staging'
  host: 'd34xwkrqkk4skr.cloudfront.net'
:production:
  bucket: 'bizevo-contents'
  host: ''
:test:
  bucket: 'bizevo-contents-test'
  host: ''
