:common:
  :authorize_url: https://slack.com/oauth/authorize
  :redirect_uri: /slack/oauth
  :token: dummy
:development:
  :client_id: ''
  :client_secret: ''
:staging:
  :client_id: ''
  :client_secret: ''
:production:
  :client_id: ''
  :client_secret: ''
:test:
  :client_id: ''
  :client_secret: ''
